package mx.com.juan.camacho.entidadesdb;
// Generated 10/09/2018 12:51:41 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Blog generated by hbm2java
 */
public class Blog  implements java.io.Serializable {


     private int id;
     private Userapp userapp;
     private String title;
     private Date FCreate;
     private String description;
     private Set comments = new HashSet(0);
     private Set tests = new HashSet(0);

    public Blog() {
    }

	
    public Blog(int id, Userapp userapp, String title, Date FCreate, String description) {
        this.id = id;
        this.userapp = userapp;
        this.title = title;
        this.FCreate = FCreate;
        this.description = description;
    }
    public Blog(int id, Userapp userapp, String title, Date FCreate, String description, Set comments, Set tests) {
       this.id = id;
       this.userapp = userapp;
       this.title = title;
       this.FCreate = FCreate;
       this.description = description;
       this.comments = comments;
       this.tests = tests;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Userapp getUserapp() {
        return this.userapp;
    }
    
    public void setUserapp(Userapp userapp) {
        this.userapp = userapp;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public Date getFCreate() {
        return this.FCreate;
    }
    
    public void setFCreate(Date FCreate) {
        this.FCreate = FCreate;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getComments() {
        return this.comments;
    }
    
    public void setComments(Set comments) {
        this.comments = comments;
    }
    public Set getTests() {
        return this.tests;
    }
    
    public void setTests(Set tests) {
        this.tests = tests;
    }




}


