package mx.com.juan.camacho.entidadesdb;
// Generated 10/09/2018 12:51:41 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Comment generated by hbm2java
 */
public class Comment  implements java.io.Serializable {


     private int id;
     private Comment comment;
     private Blog blog;
     private Userapp userapp;
     private String content;
     private Date FCreate;
     private Set comments = new HashSet(0);

    public Comment() {
    }

	
    public Comment(int id, Userapp userapp, String content, Date FCreate) {
        this.id = id;
        this.userapp = userapp;
        this.content = content;
        this.FCreate = FCreate;
    }
    public Comment(int id, Comment comment, Blog blog, Userapp userapp, String content, Date FCreate, Set comments) {
       this.id = id;
       this.comment = comment;
       this.blog = blog;
       this.userapp = userapp;
       this.content = content;
       this.FCreate = FCreate;
       this.comments = comments;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Comment getComment() {
        return this.comment;
    }
    
    public void setComment(Comment comment) {
        this.comment = comment;
    }
    public Blog getBlog() {
        return this.blog;
    }
    
    public void setBlog(Blog blog) {
        this.blog = blog;
    }
    public Userapp getUserapp() {
        return this.userapp;
    }
    
    public void setUserapp(Userapp userapp) {
        this.userapp = userapp;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public Date getFCreate() {
        return this.FCreate;
    }
    
    public void setFCreate(Date FCreate) {
        this.FCreate = FCreate;
    }
    public Set getComments() {
        return this.comments;
    }
    
    public void setComments(Set comments) {
        this.comments = comments;
    }




}


