package mx.com.juan.camacho.entidadesdb;
// Generated 2/10/2018 11:28:17 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Level generated by hbm2java
 */
public class Level  implements java.io.Serializable {


     private int id;
     private String name;
     private Set levelTests = new HashSet(0);

    public Level() {
    }

	
    public Level(int id, String name) {
        this.id = id;
        this.name = name;
    }
    public Level(int id, String name, Set levelTests) {
       this.id = id;
       this.name = name;
       this.levelTests = levelTests;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getLevelTests() {
        return this.levelTests;
    }
    
    public void setLevelTests(Set levelTests) {
        this.levelTests = levelTests;
    }




}


