package mx.com.juan.camacho.entidadesdb;
// Generated 2/10/2018 11:28:17 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Option generated by hbm2java
 */
public class Option  implements java.io.Serializable {


     private int id;
     private Question question;
     private String description;
     private boolean answer;
     private Set userappQuestions = new HashSet(0);

    public Option() {
    }

	
    public Option(int id, Question question, String description, boolean answer) {
        this.id = id;
        this.question = question;
        this.description = description;
        this.answer = answer;
    }
    public Option(int id, Question question, String description, boolean answer, Set userappQuestions) {
       this.id = id;
       this.question = question;
       this.description = description;
       this.answer = answer;
       this.userappQuestions = userappQuestions;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Question getQuestion() {
        return this.question;
    }
    
    public void setQuestion(Question question) {
        this.question = question;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public boolean isAnswer() {
        return this.answer;
    }
    
    public void setAnswer(boolean answer) {
        this.answer = answer;
    }
    public Set getUserappQuestions() {
        return this.userappQuestions;
    }
    
    public void setUserappQuestions(Set userappQuestions) {
        this.userappQuestions = userappQuestions;
    }




}


