package mx.com.juan.camacho.entidadesdb;
// Generated 12/09/2018 04:55:26 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Post generated by hbm2java
 */
public class Post  implements java.io.Serializable {


     private int id;
     private String title;
     private Date FCreate;
     private int authorUserappId;
     private String description;

    public Post() {
    }

    public Post(int id, String title, Date FCreate, int authorUserappId, String description) {
       this.id = id;
       this.title = title;
       this.FCreate = FCreate;
       this.authorUserappId = authorUserappId;
       this.description = description;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public Date getFCreate() {
        return this.FCreate;
    }
    
    public void setFCreate(Date FCreate) {
        this.FCreate = FCreate;
    }
    public int getAuthorUserappId() {
        return this.authorUserappId;
    }
    
    public void setAuthorUserappId(int authorUserappId) {
        this.authorUserappId = authorUserappId;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


