package mx.com.juan.camacho.entidadesdb;
// Generated 10/09/2018 12:51:41 PM by Hibernate Tools 4.3.1



/**
 * TestContent generated by hbm2java
 */
public class TestContent  implements java.io.Serializable {


     private int id;
     private Test test;
     private String type;
     private String content;

    public TestContent() {
    }

    public TestContent(int id, Test test, String type, String content) {
       this.id = id;
       this.test = test;
       this.type = type;
       this.content = content;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Test getTest() {
        return this.test;
    }
    
    public void setTest(Test test) {
        this.test = test;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }




}


