package mx.com.juan.camacho.entidadesdb;
// Generated 12/09/2018 04:55:26 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Test generated by hbm2java
 */
public class Test  implements java.io.Serializable {


     private int id;
     private Blog blog;
     private String name;
     private Date FCreate;
     private String content;
     private Set questions = new HashSet(0);

    public Test() {
    }

	
    public Test(int id, Blog blog, String name, Date FCreate, String content) {
        this.id = id;
        this.blog = blog;
        this.name = name;
        this.FCreate = FCreate;
        this.content = content;
    }
    public Test(int id, Blog blog, String name, Date FCreate, String content, Set questions) {
       this.id = id;
       this.blog = blog;
       this.name = name;
       this.FCreate = FCreate;
       this.content = content;
       this.questions = questions;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Blog getBlog() {
        return this.blog;
    }
    
    public void setBlog(Blog blog) {
        this.blog = blog;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getFCreate() {
        return this.FCreate;
    }
    
    public void setFCreate(Date FCreate) {
        this.FCreate = FCreate;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public Set getQuestions() {
        return this.questions;
    }
    
    public void setQuestions(Set questions) {
        this.questions = questions;
    }




}


