package mx.com.juan.camacho.entidadesdb;
// Generated 12/09/2018 04:55:26 PM by Hibernate Tools 4.3.1



/**
 * TestContent generated by hbm2java
 */
public class TestContent  implements java.io.Serializable {


     private int id;
     private String type;
     private String content;
     private int testId;

    public TestContent() {
    }

    public TestContent(int id, String type, String content, int testId) {
       this.id = id;
       this.type = type;
       this.content = content;
       this.testId = testId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public int getTestId() {
        return this.testId;
    }
    
    public void setTestId(int testId) {
        this.testId = testId;
    }




}


