package mx.com.juan.camacho.entidadesdb;
// Generated 10/09/2018 12:51:41 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Test generated by hbm2java
 */
public class Test  implements java.io.Serializable {


     private int id;
     private Blog blog;
     private String name;
     private String content;
     private Date FCreate;
     private Set testContents = new HashSet(0);
     private Set questions = new HashSet(0);

    public Test() {
    }


    public Test(int id, Blog blog, String name, String content, Date FCreate) {
        this.id = id;
        this.blog = blog;
        this.name = name;
        this.FCreate = FCreate;
        this.content = content;
    }
    public Test(int id, Blog blog, String name, String content, Date FCreate, Set testContents, Set questions) {
       this.id = id;
       this.blog = blog;
       this.name = name;
       this.FCreate = FCreate;
       this.testContents = testContents;
       this.questions = questions;
       this.content = content;
    }

    public String getContent() {
      return this.content;
    }

    public void setContent(String content) {
      this.content = content;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }
    public Blog getBlog() {
        return this.blog;
    }

    public void setBlog(Blog blog) {
        this.blog = blog;
    }
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }
    public Date getFCreate() {
        return this.FCreate;
    }

    public void setFCreate(Date FCreate) {
        this.FCreate = FCreate;
    }
    public Set getTestContents() {
        return this.testContents;
    }

    public void setTestContents(Set testContents) {
        this.testContents = testContents;
    }
    public Set getQuestions() {
        return this.questions;
    }

    public void setQuestions(Set questions) {
        this.questions = questions;
    }




}
