package mx.com.juan.camacho.entidadesdb;
// Generated 2/10/2018 11:28:17 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Test generated by hbm2java
 */
public class Test  implements java.io.Serializable {


     private int id;
     private Blog blog;
     private String name;
     private Date FCreate;
     private Set questions = new HashSet(0);
     private Set levelTests = new HashSet(0);

    public Test() {
    }

	
    public Test(int id, Blog blog, String name) {
        this.id = id;
        this.blog = blog;
        this.name = name;
    }
    public Test(int id, Blog blog, String name, Date FCreate, Set questions, Set levelTests) {
       this.id = id;
       this.blog = blog;
       this.name = name;
       this.FCreate = FCreate;
       this.questions = questions;
       this.levelTests = levelTests;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Blog getBlog() {
        return this.blog;
    }
    
    public void setBlog(Blog blog) {
        this.blog = blog;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getFCreate() {
        return this.FCreate;
    }
    
    public void setFCreate(Date FCreate) {
        this.FCreate = FCreate;
    }
    public Set getQuestions() {
        return this.questions;
    }
    
    public void setQuestions(Set questions) {
        this.questions = questions;
    }
    public Set getLevelTests() {
        return this.levelTests;
    }
    
    public void setLevelTests(Set levelTests) {
        this.levelTests = levelTests;
    }




}


