package mx.com.juan.camacho.entidadesdb;
// Generated 12/09/2018 04:55:26 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Blog generated by hbm2java
 */
public class TiempoOtro  implements java.io.Serializable {


     private int id;
     private Userapp userapp;
     private String prueba;
     private Date FInicio;
     private Date FFin;
     
     public TiempoOtro() {
    	 
     }
     
     public TiempoOtro(int id, Userapp userapp, String prueba, Date FInicio, Date FFin) {
    	 this.id = id;
    	 this.userapp = userapp;
    	 this.prueba = prueba;
    	 this.FInicio = FInicio;
    	 this.FFin = FFin;
     }

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Userapp getUserapp() {
		return userapp;
	}

	public void setUserapp(Userapp userapp) {
		this.userapp = userapp;
	}

	public String getPrueba() {
		return prueba;
	}

	public void setPrueba(String prueba) {
		this.prueba = prueba;
	}

	public Date getFInicio() {
		return FInicio;
	}

	public void setFInicio(Date fInicio) {
		FInicio = fInicio;
	}

	public Date getFFin() {
		return FFin;
	}

	public void setFFin(Date fFin) {
		FFin = fFin;
	}
     
     



}


