package mx.com.juan.camacho.entidadesdb;
// Generated 2/10/2018 11:28:17 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TiempoOtro generated by hbm2java
 */
public class TiempoOtro  implements java.io.Serializable {


     private int id;
     private Userapp userapp;
     private String prueba;
     private Date FInicio;
     private Date FFin;

    public TiempoOtro() {
    }

	
    public TiempoOtro(int id, Userapp userapp, String prueba, Date FInicio) {
        this.id = id;
        this.userapp = userapp;
        this.prueba = prueba;
        this.FInicio = FInicio;
    }
    public TiempoOtro(int id, Userapp userapp, String prueba, Date FInicio, Date FFin) {
       this.id = id;
       this.userapp = userapp;
       this.prueba = prueba;
       this.FInicio = FInicio;
       this.FFin = FFin;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Userapp getUserapp() {
        return this.userapp;
    }
    
    public void setUserapp(Userapp userapp) {
        this.userapp = userapp;
    }
    public String getPrueba() {
        return this.prueba;
    }
    
    public void setPrueba(String prueba) {
        this.prueba = prueba;
    }
    public Date getFInicio() {
        return this.FInicio;
    }
    
    public void setFInicio(Date FInicio) {
        this.FInicio = FInicio;
    }
    public Date getFFin() {
        return this.FFin;
    }
    
    public void setFFin(Date FFin) {
        this.FFin = FFin;
    }




}


