package mx.com.juan.camacho.entidadesdb;
// Generated 2/10/2018 11:28:17 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Userapp generated by hbm2java
 */
public class Userapp  implements java.io.Serializable {


     private int id;
     private String userappname;
     private String name;
     private String lastname;
     private String email;
     private String picture;
     private char sex;
     private String password;
     private Set userappQuestions = new HashSet(0);
     private Set blogs = new HashSet(0);
     private Set tiempoOtros = new HashSet(0);

    public Userapp() {
    }

	
    public Userapp(int id, String userappname, String name, String lastname, String email, char sex, String password) {
        this.id = id;
        this.userappname = userappname;
        this.name = name;
        this.lastname = lastname;
        this.email = email;
        this.sex = sex;
        this.password = password;
    }
    public Userapp(int id, String userappname, String name, String lastname, String email, String picture, char sex, String password, Set userappQuestions, Set blogs, Set tiempoOtros) {
       this.id = id;
       this.userappname = userappname;
       this.name = name;
       this.lastname = lastname;
       this.email = email;
       this.picture = picture;
       this.sex = sex;
       this.password = password;
       this.userappQuestions = userappQuestions;
       this.blogs = blogs;
       this.tiempoOtros = tiempoOtros;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getUserappname() {
        return this.userappname;
    }
    
    public void setUserappname(String userappname) {
        this.userappname = userappname;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPicture() {
        return this.picture;
    }
    
    public void setPicture(String picture) {
        this.picture = picture;
    }
    public char getSex() {
        return this.sex;
    }
    
    public void setSex(char sex) {
        this.sex = sex;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set getUserappQuestions() {
        return this.userappQuestions;
    }
    
    public void setUserappQuestions(Set userappQuestions) {
        this.userappQuestions = userappQuestions;
    }
    public Set getBlogs() {
        return this.blogs;
    }
    
    public void setBlogs(Set blogs) {
        this.blogs = blogs;
    }
    public Set getTiempoOtros() {
        return this.tiempoOtros;
    }
    
    public void setTiempoOtros(Set tiempoOtros) {
        this.tiempoOtros = tiempoOtros;
    }




}


