package mx.com.juan.camacho.entidadesdb;
// Generated 10/09/2018 12:51:41 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * UserappQuestion generated by hbm2java
 */
public class UserappQuestion  implements java.io.Serializable {


     private int id;
     private Question question;
     private Userapp userapp;
     private String answer;
     private BigDecimal earnedPoints;
     private Date dateOfGrades;

    public UserappQuestion() {
    }

	
    public UserappQuestion(int id, Question question, Userapp userapp, BigDecimal earnedPoints) {
        this.id = id;
        this.question = question;
        this.userapp = userapp;
        this.earnedPoints = earnedPoints;
    }
    public UserappQuestion(int id, Question question, Userapp userapp, String answer, BigDecimal earnedPoints, Date dateOfGrades) {
       this.id = id;
       this.question = question;
       this.userapp = userapp;
       this.answer = answer;
       this.earnedPoints = earnedPoints;
       this.dateOfGrades = dateOfGrades;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Question getQuestion() {
        return this.question;
    }
    
    public void setQuestion(Question question) {
        this.question = question;
    }
    public Userapp getUserapp() {
        return this.userapp;
    }
    
    public void setUserapp(Userapp userapp) {
        this.userapp = userapp;
    }
    public String getAnswer() {
        return this.answer;
    }
    
    public void setAnswer(String answer) {
        this.answer = answer;
    }
    public BigDecimal getEarnedPoints() {
        return this.earnedPoints;
    }
    
    public void setEarnedPoints(BigDecimal earnedPoints) {
        this.earnedPoints = earnedPoints;
    }
    public Date getDateOfGrades() {
        return this.dateOfGrades;
    }
    
    public void setDateOfGrades(Date dateOfGrades) {
        this.dateOfGrades = dateOfGrades;
    }




}


